In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [5]:
benimDizim[3:5]

array([3, 4])

In [6]:
benimDizim[3:5] = -5

In [7]:
benimDizim

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskaDizi = np.arange(0,24)

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
slicingDizisi=baskaDizi[4:9]

In [23]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [24]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
type(slicingDizisi)

numpy.ndarray

In [26]:
slicingDizisi[:] = 700

In [27]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [28]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])